import 'package:demoapp/generated/json/base/json_convert_content.dart';
import 'package:demoapp/generated/json/base/json_field.dart';

class LanguageEntity with JsonConvert<LanguageEntity> {
  @JSONField(name: "main_bottom_menu_home")
  String? mainBottomMenuHome;
  @JSONField(name: "main_bottom_menu_lotto")
  String? mainBottomMenuLotto;
  @JSONField(name: "main_bottom_menu_notifications")
  String? mainBottomMenuNotifications;
  @JSONField(name: "main_bottom_menu_profile")
  String? mainBottomMenuProfile;
  @JSONField(name: "common_confirm")
  String? commonConfirm;
  @JSONField(name: "common_reject")
  String? commonReject;
  @JSONField(name: "common_next")
  String? commonNext;
  @JSONField(name: "common_cancel")
  String? commonCancel;
  @JSONField(name: "common_search")
  String? commonSearch;
  @JSONField(name: "common_empty")
  String? commonEmpty;
  @JSONField(name: "common_yes")
  String? commonYes;
  @JSONField(name: "common_no")
  String? commonNo;
  @JSONField(name: "common_album")
  String? commonAlbum;
  @JSONField(name: "common_remark")
  String? commonRemark;
  @JSONField(name: "common_choose")
  String? commonChoose;
  @JSONField(name: "common_close")
  String? commonClose;
  @JSONField(name: "common_change")
  String? commonChange;
  @JSONField(name: "common_edit")
  String? commonEdit;
  @JSONField(name: "unit_minute")
  String? unitMinute;
  @JSONField(name: "unit_distance_km")
  String? unitDistanceKm;
  @JSONField(name: "common_deliver_to")
  String? commonDeliverTo;
  @JSONField(name: "camera_title")
  String? cameraTitle;
  @JSONField(name: "photo_library_title")
  String? photoLibraryTitle;
  @JSONField(name: "login_phone_no_hint")
  String? loginPhoneNoHint;
  @JSONField(name: "login_password_hint")
  String? loginPasswordHint;
  @JSONField(name: "login_btn_submit")
  String? loginBtnSubmit;
  @JSONField(name: "login_btn_register")
  String? loginBtnRegister;
  @JSONField(name: "login_btn_forgot_password")
  String? loginBtnForgotPassword;
  @JSONField(name: "login_btn_fb_title")
  String? loginBtnFbTitle;
  @JSONField(name: "login_title_or")
  String? loginTitleOr;
  @JSONField(name: "login_not_member_title")
  String? loginNotMemberTitle;
  @JSONField(name: "login_not_member_signup_title")
  String? loginNotMemberSignupTitle;
  @JSONField(name: "login_before_mobile_register_title")
  String? loginBeforeMobileRegisterTitle;
  @JSONField(name: "register_header")
  String? registerHeader;
  @JSONField(name: "register_input_phone_title")
  String? registerInputPhoneTitle;
  @JSONField(name: "register_input_phone_hint")
  String? registerInputPhoneHint;
  @JSONField(name: "register_otp_message")
  String? registerOtpMessage;
  @JSONField(name: "register_accept")
  String? registerAccept;
  @JSONField(name: "register_terms_and_conditions")
  String? registerTermsAndConditions;
  @JSONField(name: "register_btn_confirm")
  String? registerBtnConfirm;
  @JSONField(name: "register_btn_fb_title")
  String? registerBtnFbTitle;
  @JSONField(name: "register_btn_apple_title")
  String? registerBtnAppleTitle;
  @JSONField(name: "register_btn_mobile_phone_title")
  String? registerBtnMobilePhoneTitle;
  @JSONField(name: "channel_verification_title")
  String? channelVerificationTitle;
  @JSONField(name: "channel_verification_sms")
  String? channelVerificationSms;
  @JSONField(name: "channel_verification_voice_call")
  String? channelVerificationVoiceCall;
  @JSONField(name: "confirm_otp_title")
  String? confirmOtpTitle;
  @JSONField(name: "confirm_otp_message")
  String? confirmOtpMessage;
  @JSONField(name: "confirm_otp_send_again")
  String? confirmOtpSendAgain;
  @JSONField(name: "confirm_otp_waiting_send_again")
  String? confirmOtpWaitingSendAgain;
  String? second;
  @JSONField(name: "confirm_otp_reference")
  String? confirmOtpReference;
  @JSONField(name: "user_info_header")
  String? userInfoHeader;
  @JSONField(name: "user_info_firstname")
  String? userInfoFirstname;
  @JSONField(name: "user_info_firstname_hint")
  String? userInfoFirstnameHint;
  @JSONField(name: "user_info_lastname")
  String? userInfoLastname;
  @JSONField(name: "user_info_lastname_hint")
  String? userInfoLastnameHint;
  @JSONField(name: "user_info_gender")
  String? userInfoGender;
  @JSONField(name: "user_info_birthday")
  String? userInfoBirthday;
  @JSONField(name: "user_info_gender_hint")
  String? userInfoGenderHint;
  @JSONField(name: "user_info_birthday_hint")
  String? userInfoBirthdayHint;
  @JSONField(name: "user_info_alert_title")
  String? userInfoAlertTitle;
  @JSONField(name: "create_password_header")
  String? createPasswordHeader;
  @JSONField(name: "create_password_title")
  String? createPasswordTitle;
  @JSONField(name: "create_password_help")
  String? createPasswordHelp;
  @JSONField(name: "create_password_again_title")
  String? createPasswordAgainTitle;
  @JSONField(name: "create_user_success_title")
  String? createUserSuccessTitle;
  @JSONField(name: "create_user_success_start")
  String? createUserSuccessStart;
  @JSONField(name: "forgot_password_title")
  String? forgotPasswordTitle;
  @JSONField(name: "forgot_password_phone_no")
  String? forgotPasswordPhoneNo;
  @JSONField(name: "forgot_password_phone_no_hint")
  String? forgotPasswordPhoneNoHint;
  @JSONField(name: "forgot_password_message")
  String? forgotPasswordMessage;
  @JSONField(name: "forgot_password_create_new_password")
  String? forgotPasswordCreateNewPassword;
  String? profile;
  @JSONField(name: "profile_title")
  String? profileTitle;
  @JSONField(name: "profile_edit")
  String? profileEdit;
  @JSONField(name: "profile_info")
  String? profileInfo;
  @JSONField(name: "profile_setting")
  String? profileSetting;
  @JSONField(name: "profile_help_center")
  String? profileHelpCenter;
  @JSONField(name: "profile_contact_us")
  String? profileContactUs;
  @JSONField(name: "profile_terms_of_service")
  String? profileTermsOfService;
  @JSONField(name: "profile_privacy_policy")
  String? profilePrivacyPolicy;
  @JSONField(name: "setting_title")
  String? settingTitle;
  @JSONField(name: "setting_edit_profile")
  String? settingEditProfile;
  @JSONField(name: "setting_notification")
  String? settingNotification;
  @JSONField(name: "setting_change_language")
  String? settingChangeLanguage;
  @JSONField(name: "setting_change_password")
  String? settingChangePassword;
  @JSONField(name: "setting_logout")
  String? settingLogout;
  @JSONField(name: "setting_current_version")
  String? settingCurrentVersion;
  @JSONField(name: "edit_profile_title")
  String? editProfileTitle;
  @JSONField(name: "edit_profile_phone_no")
  String? editProfilePhoneNo;
  @JSONField(name: "edit_profile_name")
  String? editProfileName;
  @JSONField(name: "edit_profile_name_hint")
  String? editProfileNameHint;
  @JSONField(name: "edit_profile_last_name")
  String? editProfileLastName;
  @JSONField(name: "edit_profile_last_name_hint")
  String? editProfileLastNameHint;
  @JSONField(name: "edit_profile_birthday")
  String? editProfileBirthday;
  @JSONField(name: "edit_profile_choose_birth_date")
  String? editProfileChooseBirthDate;
  @JSONField(name: "edit_profile_gender")
  String? editProfileGender;
  @JSONField(name: "edit_profile_select_gender")
  String? editProfileSelectGender;
  @JSONField(name: "edit_profile_save")
  String? editProfileSave;
  @JSONField(name: "edit_profile_photo_camera_error_message")
  String? editProfilePhotoCameraErrorMessage;
  @JSONField(name: "edit_profile_photo_library_error_message")
  String? editProfilePhotoLibraryErrorMessage;
  @JSONField(name: "gender_dialog_title")
  String? genderDialogTitle;
  @JSONField(name: "gender_dialog_male")
  String? genderDialogMale;
  @JSONField(name: "gender_dialog_female")
  String? genderDialogFemale;
  @JSONField(name: "gender_dialog_everyone")
  String? genderDialogEveryone;
  @JSONField(name: "gender_dialog_not_specified")
  String? genderDialogNotSpecified;
  String? male;
  String? female;
  String? unknown;
  @JSONField(name: "change_password_title")
  String? changePasswordTitle;
  @JSONField(name: "change_password_old_password")
  String? changePasswordOldPassword;
  @JSONField(name: "change_password_old_password_hint")
  String? changePasswordOldPasswordHint;
  @JSONField(name: "change_password_new_password")
  String? changePasswordNewPassword;
  @JSONField(name: "change_password_new_password_hint")
  String? changePasswordNewPasswordHint;
  @JSONField(name: "change_password_new_password_help")
  String? changePasswordNewPasswordHelp;
  @JSONField(name: "change_password_new_password_again")
  String? changePasswordNewPasswordAgain;
  @JSONField(name: "error_dialog")
  String? errorDialog;
  @JSONField(name: "action_sheet_camera")
  String? actionSheetCamera;
  @JSONField(name: "action_sheet_photo_library")
  String? actionSheetPhotoLibrary;
  @JSONField(name: "action_sheet_profile_image")
  String? actionSheetProfileImage;
  @JSONField(name: "action_cancel")
  String? actionCancel;
  @JSONField(name: "country_select_title")
  String? countrySelectTitle;
  @JSONField(name: "notification_header")
  String? notificationHeader;
  @JSONField(name: "notification_promotion_title")
  String? notificationPromotionTitle;
  @JSONField(name: "notification_activity_title")
  String? notificationActivityTitle;
  @JSONField(name: "notification_section_title")
  String? notificationSectionTitle;
  @JSONField(name: "notification_activity_desc")
  String? notificationActivityDesc;
  @JSONField(name: "notification_promotion_desc")
  String? notificationPromotionDesc;
  @JSONField(name: "error_dialog_title")
  String? errorDialogTitle;
  @JSONField(name: "error_internet")
  String? errorInternet;
  @JSONField(name: "error_server_down")
  String? errorServerDown;
  @JSONField(name: "error_timeout")
  String? errorTimeout;
  @JSONField(name: "error_data_not_found")
  String? errorDataNotFound;
  @JSONField(name: "error_not_enough_coins")
  String? errorNotEnoughCoins;
  @JSONField(name: "current_language")
  String? currentLanguage;
  @JSONField(name: "profile_guest_desc")
  String? profileGuestDesc;
  String? confirmation;
  @JSONField(name: "profile_update_password_success")
  String? profileUpdatePasswordSuccess;
  @JSONField(name: "profile_create_password_success")
  String? profileCreatePasswordSuccess;
  @JSONField(name: "validate_password_not_matched")
  String? validatePasswordNotMatched;
  @JSONField(name: "validate_text_field_fill_up_text")
  String? validateTextFieldFillUpText;
  @JSONField(name: "validate_text_field_password_text")
  String? validateTextFieldPasswordText;
  @JSONField(name: "validate_text_field_password_check_characters_text")
  String? validateTextFieldPasswordCheckCharactersText;
  @JSONField(name: "validate_text_field_phone_number_length_text")
  String? validateTextFieldPhoneNumberLengthText;
  @JSONField(name: "validate_text_field_phone_number_length_20_text")
  String? validateTextFieldPhoneNumberLength20Text;
  @JSONField(name: "validate_text_field_phone_number_invalid_text")
  String? validateTextFieldPhoneNumberInvalidText;
  @JSONField(name: "validate_text_field_first_name_length_20_text")
  String? validateTextFieldFirstNameLength20Text;
  @JSONField(name: "validate_text_field_first_name_check_characters_text")
  String? validateTextFieldFirstNameCheckCharactersText;
  @JSONField(name: "validate_text_field_last_name_length_20_text")
  String? validateTextFieldLastNameLength20Text;
  @JSONField(name: "validate_text_field_last_name_check_characters_text")
  String? validateTextFieldLastNameCheckCharactersText;
  @JSONField(name: "select_address_title")
  String? selectAddressTitle;
  @JSONField(name: "select_address_favorites")
  String? selectAddressFavorites;
  @JSONField(name: "select_address_home")
  String? selectAddressHome;
  @JSONField(name: "select_address_work")
  String? selectAddressWork;
  @JSONField(name: "select_address_other")
  String? selectAddressOther;
  @JSONField(name: "select_address_add_address")
  String? selectAddressAddAddress;
  @JSONField(name: "hint_input_home")
  String? hintInputHome;
  @JSONField(name: "create_address_save_place")
  String? createAddressSavePlace;
  @JSONField(name: "modal_over_distance_title")
  String? modalOverDistanceTitle;
  @JSONField(name: "modal_over_distance_desc")
  String? modalOverDistanceDesc;
  @JSONField(name: "modal_over_distance_change_address")
  String? modalOverDistanceChangeAddress;
  @JSONField(name: "user_location_tile")
  String? userLocationTile;
  @JSONField(name: "user_location_desc")
  String? userLocationDesc;
  @JSONField(name: "user_location_allow_location")
  String? userLocationAllowLocation;
  @JSONField(name: "user_location_enter_my_location")
  String? userLocationEnterMyLocation;
  @JSONField(name: "user_location_use_location")
  String? userLocationUseLocation;
  @JSONField(name: "user_location_this_your_location")
  String? userLocationThisYourLocation;
  @JSONField(name: "user_location_skip_step")
  String? userLocationSkipStep;
  @JSONField(name: "user_location_last_entered")
  String? userLocationLastEntered;
  @JSONField(name: "user_location_your_location")
  String? userLocationYourLocation;
  @JSONField(name: "user_location_favorite_places")
  String? userLocationFavoritePlaces;
  @JSONField(name: "all_categories")
  String? allCategories;
  @JSONField(name: "select_by_category")
  String? selectByCategory;
  @JSONField(name: "see_all")
  String? seeAll;
  String? menu;
  @JSONField(name: "popular_menu")
  String? popularMenu;
  @JSONField(name: "recommended_menu")
  String? recommendedMenu;
  @JSONField(name: "delivery_address")
  String? deliveryAddress;
  @JSONField(name: "address_save_place")
  String? addressSavePlace;
  @JSONField(name: "address_save_place_desc")
  String? addressSavePlaceDesc;
  @JSONField(name: "use_current_location")
  String? useCurrentLocation;
  @JSONField(name: "payment_method")
  String? paymentMethod;
  String? ccw;
  String? ibanking;
  String? free;
  String? banktrans;
  String? cod;
  String? promptpay;
  @JSONField(name: "internet_banking_bbl")
  String? internetBankingBbl;
  @JSONField(name: "internet_banking_scb")
  String? internetBankingScb;
  @JSONField(name: "internet_banking_ktb")
  String? internetBankingKtb;
  @JSONField(name: "internet_banking_bay")
  String? internetBankingBay;
  @JSONField(name: "internet_banking_tbank")
  String? internetBankingTbank;
  @JSONField(name: "ibanking_desc1")
  String? ibankingDesc1;
  @JSONField(name: "ibanking_desc2")
  String? ibankingDesc2;
  @JSONField(name: "ibanking_desc3")
  String? ibankingDesc3;
  @JSONField(name: "sub_total")
  String? subTotal;
  String? shipping;
  String? tax;
  @JSONField(name: "payment_fee")
  String? paymentFee;
  String? discount;
  String? total;
  @JSONField(name: "free-shipping")
  String? freeShipping;
  @JSONField(name: "checkout_deliver_to")
  String? checkoutDeliverTo;
  @JSONField(name: "checkout_title_order")
  String? checkoutTitleOrder;
  @JSONField(name: "checkout_payment_method")
  String? checkoutPaymentMethod;
  @JSONField(name: "checkout_grand_total")
  String? checkoutGrandTotal;
  @JSONField(name: "checkout_confirmation")
  String? checkoutConfirmation;
  @JSONField(name: "checkout_remark")
  String? checkoutRemark;
  @JSONField(name: "verify_account")
  String? verifyAccount;
  @JSONField(name: "unverify_account")
  String? unverifyAccount;
  String? ordered;
  String? reserved;
  String? cancelled;
  @JSONField(name: "version_title")
  String? versionTitle;
  @JSONField(name: "version_desc")
  String? versionDesc;
  @JSONField(name: "version_update_later")
  String? versionUpdateLater;
  @JSONField(name: "version_update_now")
  String? versionUpdateNow;
  @JSONField(name: "version_force_update")
  String? versionForceUpdate;
}
